function checkForToolboxes

if ~license('test','symbolic_toolbox')
    bigString=['Symbolic Math Toolbox not installed. This is only used'...
               'to calculate secular determinants. If you want to install it, look '...
               'at the ''Home'' tab of the Desktop and click on the icon '...
               'matching the one on the left. This opens the ''Add-On Explorer.'' '...
               'Then search for ''Symbolic Math Toolbox'' and click install it.'];
    myTitle=('Toolbox not installed');
    myIcon=imread('addons.png');
    msgbox(bigString,myTitle,'custom',myIcon);
end